version: "3"
services:
  app:
    build:
    container_name: todo-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todoapp
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
      - PORT=5003
